# File generated by Flopy version 3.3.5 on 03/04/2022 at 11:14:03.
BEGIN attributes
  NAMES  FLOWRATE
  METHODS  LINEAREND
END attributes

BEGIN timeseries
       0.00000000    2000.00000000
     307.00000000    6000.00000000
     791.00000000    5000.00000000
    1000.00000000    9000.00000000
END timeseries

