# File generated by Flopy version 3.3.5 on 03/04/2022 at 11:13:36.
BEGIN attributes
  NAMES  rch_3
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00170000
       1.00000000       0.00200000
      11.00000000       0.00170000
      21.00000000       0.00180000
      31.00000000       0.00200000
END timeseries

