# File generated by Flopy version 3.3.5 on 03/04/2022 at 11:13:36.
BEGIN attributes
  NAMES  well_1_rate  well_2_rate  well_6_rate
  METHODS  stepwise  stepwise  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00000000       0.00000000       0.00000000
       1.00000000    -200.00000000       0.00000000    -100.00000000
      11.00000000   -1800.00000000    -500.00000000    -200.00000000
      21.00000000    -200.00000000    -400.00000000    -300.00000000
      31.00000000       0.00000000    -600.00000000    -400.00000000
END timeseries

