
{% set data = load_setup_py_data() %}

package:
  name: pymf6
  version: {{ data.get('version') }}

source:
  path: ../..

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.19

  run:
    - numpy
    - matplotlib
    - flopy
    - m2w64-toolchain  # [win]
    - frozendict

about:
  home: hydrocomputing
  license: MIT
