
{% set data = load_setup_py_data() %}

package:
  name: pymf6
  version: {{ data.get('version') }}

source:
  path: ../..

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - numpy
    - m2w64-toolchain  # [win]

about:
  home: hydrocomputing
  license: MIT

